import json
from pathlib import Path

MARKER = "<!-- prcopilot-report -->"

def load_json(path: Path):
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}

def summarize_diff(diff: dict):
    changes = diff.get("changes")
    if isinstance(changes, list):
        return len(changes), changes
    if isinstance(changes, dict):
        return 1, changes
    return 0, diff

def summarize_contract(report: dict):
    failed = report.get("failed_checks")
    total = report.get("total_checks")
    if isinstance(failed, int) and isinstance(total, int):
        return total, failed, report.get("results", [])
    results = report.get("results", [])
    if isinstance(results, list) and results:
        total = len(results)
        failed = sum(1 for r in results if r.get("passed") is False)
        return total, failed, results
    return 0, 0, []

def main():
    diff = load_json(Path("artifacts/diff.json"))
    contract = load_json(Path("artifacts/contract_report.json"))

    n_changes, changes_obj = summarize_diff(diff)
    total_checks, failed_checks, _ = summarize_contract(contract)

    status = "PASS"
    if failed_checks > 0:
        status = "FAIL"

    md = []
    md.append(MARKER)
    md.append("## PR Copilot Report")
    md.append("")
    md.append(f"**Status:** {status}")
    md.append("")
    md.append(f"**Schema changes:** {n_changes}")
    md.append(f"**Contract checks:** {total_checks} total, {failed_checks} failed")
    md.append("")
    md.append("<details><summary>Schema diff details</summary>")
    md.append("")
    md.append("```json")
    md.append(json.dumps(diff, indent=2)[:12000])
    md.append("```")
    md.append("</details>")
    md.append("")
    md.append("<details><summary>Contract check details</summary>")
    md.append("")
    md.append("```json")
    md.append(json.dumps(contract, indent=2)[:12000])
    md.append("```")
    md.append("</details>")
    md.append("")
    md.append("_Generated by prcopilot CI_")

    Path("artifacts").mkdir(parents=True, exist_ok=True)
    Path("artifacts/pr_comment.md").write_text("\n".join(md) + "\n", encoding="utf-8")

if __name__ == "__main__":
    main()
