import json
from pathlib import Path

def safe_load(path: Path):
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None

def main():
    diff = safe_load(Path("artifacts/diff.json")) or {}
    contract = safe_load(Path("artifacts/contract_report.json")) or {}

    # Heuristics: keep it robust even if JSON shape changes
    diff_changes = diff.get("changes") or diff.get("summary") or diff
    contract_status = contract.get("status") or contract.get("result") or contract.get("summary") or contract

    md = []
    md.append("## PR Copilot Report")
    md.append("")
    md.append("### Schema Diff")
    md.append("```json")
    md.append(json.dumps(diff_changes, indent=2)[:12000])
    md.append("```")
    md.append("")
    md.append("### Contract Checks")
    md.append("```json")
    md.append(json.dumps(contract_status, indent=2)[:12000])
    md.append("```")
    md.append("")
    md.append("_Generated by prcopilot CI_")

    Path("artifacts/pr_comment.md").parent.mkdir(parents=True, exist_ok=True)
    Path("artifacts/pr_comment.md").write_text("\n".join(md) + "\n", encoding="utf-8")

if __name__ == "__main__":
    main()
